In [7]:
import torch

In [2]:
## debug some parser stuff
#https://github.com/allenai/allennlp/pull/1544/commits/e7d3713194b285d7fde19deccd5375677a06b95d
# head sentinel is a random vector that you attach to the start of the sentence -- avoids having to do things like adding dummy root node to all inputs, e.g. [root] + tokens
# [root] + pos
# e.g. adding dummy root tokens into everything...

In [26]:
batch_size = 4
seq_len = 10
dim = 10

In [28]:
head_sentinel = torch.nn.Parameter(torch.randn([1, 1, dim]))
print(head_sentinel.shape)
print(head_sentinel)

torch.Size([1, 1, 10])
Parameter containing:
tensor([[[-0.3128,  0.8670, -0.7462,  0.1871, -0.5698, -0.1392,  0.2054,
           0.9493, -1.0815,  0.3115]]], requires_grad=True)


In [24]:
# head_sentinel: (batch, 1, hidden_dim * 2)
head_sentinel = x.expand(1, 1, 10)
print(head_sentinel.shape)
print(head_sentinel)

torch.Size([1, 1, 10])
tensor([[[-0.0947,  0.1922,  1.1096,  0.0598,  0.6625,  1.1269,  0.9848,
           0.3025, -0.1626, -0.7083]]], grad_fn=<ExpandBackward>)


In [30]:
encoded_text = torch.randn(batch_size, seq_len, dim)
print(encoded_text.shape)
print(encoded_text)

torch.Size([4, 10, 10])
tensor([[[-9.6737e-01,  7.2086e-01, -9.8140e-01, -2.0691e+00,  3.2324e-01,
          -2.8798e-01,  9.7985e-01,  2.2759e-01,  8.6093e-01, -5.2002e-01],
         [ 2.5157e-02,  4.1099e-01, -3.4186e-01, -1.5887e+00,  7.4706e-01,
          -5.0874e-01, -2.0922e+00, -3.0475e-01,  1.2960e+00,  1.3063e+00],
         [-2.1481e-01, -4.2873e-01, -1.2328e+00,  8.1656e-01, -4.8023e-01,
          -4.7914e-01, -2.1925e-01,  1.5066e-01, -1.0041e+00, -1.9839e-01],
         [ 2.1849e+00, -1.8040e-01,  1.5261e-01,  4.8069e-01,  7.1790e-01,
           9.0408e-01, -1.2656e+00,  1.5773e+00, -1.0600e-01, -9.9923e-01],
         [-8.9860e-01,  2.5348e-01, -9.0696e-01,  6.0079e-01, -1.0658e+00,
          -7.6177e-01, -1.3353e+00, -4.3056e-02, -5.4334e-01,  1.7369e+00],
         [-8.8177e-01, -6.6179e-02,  1.9930e+00, -2.7323e+00,  9.0598e-01,
           9.5027e-02, -1.0333e+00, -1.5909e-01, -4.8424e-01, -5.6134e-02],
         [ 1.9670e-01,  6.4806e-01,  1.1023e-01,  5.7225e-01,  7.4889e

In [31]:
# expand the random vector to batch size
head_sentinel = head_sentinel.expand(batch_size, 1, dim)
print(head_sentinel.shape)
print(head_sentinel)

torch.Size([4, 1, 10])
tensor([[[-0.3128,  0.8670, -0.7462,  0.1871, -0.5698, -0.1392,  0.2054,
           0.9493, -1.0815,  0.3115]],

        [[-0.3128,  0.8670, -0.7462,  0.1871, -0.5698, -0.1392,  0.2054,
           0.9493, -1.0815,  0.3115]],

        [[-0.3128,  0.8670, -0.7462,  0.1871, -0.5698, -0.1392,  0.2054,
           0.9493, -1.0815,  0.3115]],

        [[-0.3128,  0.8670, -0.7462,  0.1871, -0.5698, -0.1392,  0.2054,
           0.9493, -1.0815,  0.3115]]], grad_fn=<ExpandBackward>)


In [32]:
# Concatenate the head sentinel onto the sentence representation.
encoded_text = torch.cat([head_sentinel, encoded_text], 1)
print(encoded_text.shape)
print(encoded_text)

torch.Size([4, 11, 10])
tensor([[[-3.1280e-01,  8.6699e-01, -7.4618e-01,  1.8715e-01, -5.6982e-01,
          -1.3918e-01,  2.0538e-01,  9.4934e-01, -1.0815e+00,  3.1146e-01],
         [-9.6737e-01,  7.2086e-01, -9.8140e-01, -2.0691e+00,  3.2324e-01,
          -2.8798e-01,  9.7985e-01,  2.2759e-01,  8.6093e-01, -5.2002e-01],
         [ 2.5157e-02,  4.1099e-01, -3.4186e-01, -1.5887e+00,  7.4706e-01,
          -5.0874e-01, -2.0922e+00, -3.0475e-01,  1.2960e+00,  1.3063e+00],
         [-2.1481e-01, -4.2873e-01, -1.2328e+00,  8.1656e-01, -4.8023e-01,
          -4.7914e-01, -2.1925e-01,  1.5066e-01, -1.0041e+00, -1.9839e-01],
         [ 2.1849e+00, -1.8040e-01,  1.5261e-01,  4.8069e-01,  7.1790e-01,
           9.0408e-01, -1.2656e+00,  1.5773e+00, -1.0600e-01, -9.9923e-01],
         [-8.9860e-01,  2.5348e-01, -9.0696e-01,  6.0079e-01, -1.0658e+00,
          -7.6177e-01, -1.3353e+00, -4.3056e-02, -5.4334e-01,  1.7369e+00],
         [-8.8177e-01, -6.6179e-02,  1.9930e+00, -2.7323e+00,  9.0598e

In [40]:
mask = torch.ones(batch_size, seq_len)
print(mask.shape)
print(mask)
# just pad the last element
mask[(0,-1)] = 0
mask[(1,-1)] = 0
mask[(2,-1)] = 0
mask[(3,-1)] = 0
print(mask.shape)
print(mask)

torch.Size([4, 10])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
torch.Size([4, 10])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])


In [41]:
mask = torch.cat([mask.new_ones(batch_size, 1), mask], 1)
print(mask.shape)
print(mask)

torch.Size([4, 11])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])


In [50]:
head_indices = torch.LongTensor(batch_size, seq_len).random_(0, 10)
print(head_indices.shape)
print(head_indices)

torch.Size([4, 10])
tensor([[5, 1, 3, 0, 0, 1, 4, 2, 3, 0],
        [5, 7, 8, 2, 0, 6, 0, 6, 9, 3],
        [9, 9, 3, 0, 9, 8, 2, 4, 8, 9],
        [5, 3, 2, 9, 8, 6, 0, 3, 5, 8]])


In [51]:
head_indices = torch.cat([head_indices.new_zeros(batch_size, 1), head_indices], 1)
print(head_indices.shape)
print(head_indices)

torch.Size([4, 11])
tensor([[0, 5, 1, 3, 0, 0, 1, 4, 2, 3, 0],
        [0, 5, 7, 8, 2, 0, 6, 0, 6, 9, 3],
        [0, 9, 9, 3, 0, 9, 8, 2, 4, 8, 9],
        [0, 5, 3, 2, 9, 8, 6, 0, 3, 5, 8]])


In [60]:
float_mask = mask.float()
minus_inf = -1e8
# -.0 where ones are usually otherwise the 1 is multiplid by -inf
minus_mask = (1 - float_mask) * minus_inf
# add minus mask to attended arcs (mask out values we don't want?)
print(minus_mask.shape)
print(minus_mask)

torch.Size([4, 11])
tensor([[        -0.,         -0.,         -0.,         -0.,         -0.,
                 -0.,         -0.,         -0.,         -0.,         -0.,
         -100000000.],
        [        -0.,         -0.,         -0.,         -0.,         -0.,
                 -0.,         -0.,         -0.,         -0.,         -0.,
         -100000000.],
        [        -0.,         -0.,         -0.,         -0.,         -0.,
                 -0.,         -0.,         -0.,         -0.,         -0.,
         -100000000.],
        [        -0.,         -0.,         -0.,         -0.,         -0.,
                 -0.,         -0.,         -0.,         -0.,         -0.,
         -100000000.]])


In [59]:
attended_arcs = torch.randn(batch_size, seq_len+1, seq_len+1)
print(attended_arcs.shape)
print(attended_arcs)

torch.Size([4, 11, 11])
tensor([[[-9.8183e-01,  1.1594e+00, -2.0109e+00,  5.6744e-01, -3.8066e-02,
           7.0324e-01, -1.7452e+00, -8.7935e-02,  2.4882e-01,  8.6160e-01,
           5.2000e-01],
         [-5.9327e-01, -1.3349e+00, -9.4245e-01, -3.8243e-01, -3.6044e-01,
           1.8792e+00, -2.3008e+00, -1.8833e-01, -1.5625e+00, -1.0101e+00,
          -6.0017e-01],
         [ 5.8026e-02,  1.5312e+00, -3.3651e-01,  8.5580e-01,  5.4043e-02,
          -8.2895e-01,  8.9131e-01,  4.5121e-01,  2.0602e+00,  3.5775e-01,
           6.2936e-01],
         [-8.6685e-01, -3.3771e-01, -6.0243e-01, -1.5533e+00, -2.9116e-01,
           1.2682e+00, -2.3876e-01, -5.0341e-01, -3.1285e-02, -7.2232e-01,
           5.9311e-02],
         [-3.0391e-01,  7.9372e-01,  7.3996e-01,  1.5863e+00, -1.5021e+00,
          -7.4746e-01,  6.3929e-01, -7.1581e-02,  7.0488e-01, -4.0408e-01,
          -1.1169e+00],
         [-6.8853e-01,  9.1334e-01,  2.5664e-01, -1.0112e-01, -2.7055e+00,
           1.2839e+00,  9.6319e

In [61]:
attended_arcs = attended_arcs + minus_mask.unsqueeze(2) + minus_mask.unsqueeze(1)
print(attended_arcs.shape)
print(attended_arcs)

torch.Size([4, 11, 11])
tensor([[[-9.8183e-01,  1.1594e+00, -2.0109e+00,  5.6744e-01, -3.8066e-02,
           7.0324e-01, -1.7452e+00, -8.7935e-02,  2.4882e-01,  8.6160e-01,
          -1.0000e+08],
         [-5.9327e-01, -1.3349e+00, -9.4245e-01, -3.8243e-01, -3.6044e-01,
           1.8792e+00, -2.3008e+00, -1.8833e-01, -1.5625e+00, -1.0101e+00,
          -1.0000e+08],
         [ 5.8026e-02,  1.5312e+00, -3.3651e-01,  8.5580e-01,  5.4043e-02,
          -8.2895e-01,  8.9131e-01,  4.5121e-01,  2.0602e+00,  3.5775e-01,
          -1.0000e+08],
         [-8.6685e-01, -3.3771e-01, -6.0243e-01, -1.5533e+00, -2.9116e-01,
           1.2682e+00, -2.3876e-01, -5.0341e-01, -3.1285e-02, -7.2232e-01,
          -1.0000e+08],
         [-3.0391e-01,  7.9372e-01,  7.3996e-01,  1.5863e+00, -1.5021e+00,
          -7.4746e-01,  6.3929e-01, -7.1581e-02,  7.0488e-01, -4.0408e-01,
          -1.0000e+08],
         [-6.8853e-01,  9.1334e-01,  2.5664e-01, -1.0112e-01, -2.7055e+00,
           1.2839e+00,  9.6319e

In [ ]:
head indices tensor([[7, 3, 7, 7, 7, 7, 0, 9, 7, 7],
        [2, 0, 5, 5, 2, 8, 8, 5, 2, 0],
        [3, 1, 4, 0, 4, 8, 8, 4, 4, 0],
        [3, 3, 4, 0, 6, 4, 9, 9, 6, 4],
        [2, 0, 6, 6, 6, 2, 8, 6, 2, 0],
        [2, 0, 2, 3, 6, 2, 9, 9, 6, 2],
        [3, 3, 0, 7, 7, 7, 3, 7, 3, 0],
        [4, 4, 4, 8, 3, 7, 8, 0, 8, 0],
        [3, 3, 6, 6, 6, 0, 9, 9, 6, 6],
        [4, 4, 4, 0, 6, 4, 8, 4, 4, 0],
        [5, 5, 5, 5, 0, 8, 8, 5, 5, 0],
        [2, 0, 5, 5, 2, 9, 9, 9, 2, 2],
        [2, 3, 0, 6, 6, 3, 9, 9, 3, 3],
        [3, 3, 0, 3, 8, 8, 3, 7, 3, 0],
        [6, 1, 6, 6, 6, 0, 9, 9, 6, 6],
        [3, 3, 0, 3, 6, 4, 8, 6, 3, 0],
        [6, 6, 4, 6, 6, 0, 9, 9, 6, 6],
        [2, 0, 2, 6, 6, 2, 6, 9, 6, 2],
        [5, 5, 5, 5, 0, 7, 5, 5, 5, 0],
        [2, 4, 4, 0, 4, 9, 9, 5, 8, 4],
        [2, 0, 4, 2, 4, 4, 2, 2, 2, 0],
        [2, 0, 4, 2, 7, 7, 2, 9, 7, 2],
        [4, 4, 4, 0, 4, 4, 8, 4, 4, 0],
        [3, 3, 5, 5, 0, 7, 5, 9, 7, 5],
        [2, 8, 5, 5, 2, 8, 8, 0, 8, 0],
        [2, 5, 5, 5, 0, 8, 6, 5, 5, 0],
        [5, 5, 5, 5, 0, 7, 5, 7, 5, 5],
        [7, 3, 7, 7, 7, 7, 0, 9, 7, 7],
        [0, 4, 4, 1, 1, 1, 6, 9, 6, 1],
        [4, 4, 4, 0, 8, 8, 8, 4, 4, 0],
        [5, 5, 4, 5, 0, 8, 8, 5, 5, 0],
        [4, 4, 4, 0, 4, 4, 4, 9, 4, 9]], device='cuda:0')


mask tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:0')


In [19]:
#[head_indices.new_zeros(batch_size, 1)
a = torch.rand(4,3)
print(a)

b = a.new_zeros(4,1)
print(b)

c = torch.cat((a,b), 1)
print(c)

tensor([[0.4717, 0.7192, 0.6074],
        [0.0790, 0.9294, 0.0374],
        [0.1606, 0.2051, 0.0593],
        [0.9422, 0.9595, 0.6442]])
tensor([[0.],
        [0.],
        [0.],
        [0.]])
tensor([[0.4717, 0.7192, 0.6074, 0.0000],
        [0.0790, 0.9294, 0.0374, 0.0000],
        [0.1606, 0.2051, 0.0593, 0.0000],
        [0.9422, 0.9595, 0.6442, 0.0000]])


In [ ]:
        attended_arcs : ``torch.Tensor``, required.
            A tensor of shape (batch_size, sequence_length, sequence_length) used to generate
            a distribution over attachments of a given word to all other words.